export default {
  session_b: {
    label: 'November 14, 9.15 AM - 10.45 AM B',
    b1: 'Curriculum and pedagogy',
    b2: 'Equity and inclusion',
    b3: 'Health, nutrition, and well-being',
    b4: 'ECCE in emergencies',
    b5: 'School readiness and the role of assessment',
  },
  session_c: {
    label: 'November 14, 11.00 AM - 12.30 PM C',
    c1: 'ECCE teacher and caregiver development systems',
    c2: 'ECCE workforce professionalization',
    c3: 'Supervision and leadership',
    c4: 'Gender and teaching',
    c5: 'Parenting',
  },
  session_d: {
    label: 'November 14, 14.00 PM - 15.30 PM D',
    d1: 'Data, monitoring and evaluation',
    d2: 'ECCE rights and legal framework',
    d3: 'Financing and partnerships',
    d4: 'Building quality ECCE systems for all',
    d5: 'Whole-of-government approach, multisectorality and coordination',
  },
  session_e: {
    label: 'November 14, 15.30 PM - 17.00 PM E',
    e1: 'Neurosciences to advance the ECCE agenda',
    e2: 'Technology and artificial intelligence',
    e3: 'Designing innovative learning practices and spaces',
    e4: 'Alternative models of ECCE provision',
    e5: 'Greening ECCE',
  },
  session_f: {
    label: 'November 14, 17.30 PM - 18.30 PM F',
    f1: 'Harnessing a global network for the ECCE workforce development. Press conference',
    f2: 'Tools for Transformation: Strategies for building a gendertransformative pre-primary education system.',
    f3: 'Childhood Care and Education in times of crisis: Best practice and advocacy opportunities',
    f4: 'Home-based childcare services in labour intensive communities to ensure Early Childhood Care and Education.',
    f5: 'Equal Parenting: A must for Early Childhood Development and for a transformative tomorrow.',
    f6: 'Transformative ECCE Through Social and Emotional Learning.',
  },
  session_g: {
    label: 'November 15, 8.00 AM - 9.00 AM G',
    g1: 'How philanthropy can accelerate ECCE system reform.',
    g2: 'Early Childhood Educators: Raising the Status of the Profession.',
    g3: 'Programme national marocain pour la généralisation de l’éducation préscolaire 2018 – 2028.',
    g4: 'Investing in Early Childhood Education for Sustainable Development and Improved Outcomes.',
    g5: 'Infants and toddlers – children playing for a sustainable life.',
  },
  session_h: {
    label: 'November 15, 9.00 AM - 10.00 AM H',
    h1: '10 years of the ILO Policy Guidelines on the promotion of decent work for early childhood education personnel.',
    h2: 'Listening to Regional Voices and Experiences: Sankofa and Sub- Saharan Africa.',
    h3: 'Promoting the scaleup of equitable and quality ECCE service provision through adequate resource mobilization and strong advocacy.',
    h4: 'Right from the Start: The role of civil society actors and partnerships in advancing ECCE.',
    h5: 'Accelerating access and quality to ECCE in Uzbekistan: Learning from coordinated efforts between the Government, UNICEF and the World Bank.',
  },
};
